### ISSUE TITLE
Not able to add Markets

### ISSUE THREAD

**Issue by jlhems** [SaveTheChildrenUK/CostOfTheDiet#35]
Hi Jason

I'm trying to set up a new assessment. The + button in the Markets section doesn't work, I can't add any markets. Also when I hit the Back button it takes me to the attached screenshot, not the main Assessments Details screen.
<img width="1128" alt="Back screen from Markets page" src="https://user-images.githubusercontent.com/89542648/161975950-b18680b9-bf31-4c36-b6b3-af1f43307bfc.PNG">

**Comment by Zerodriven** [comment]
Hi @jlhems 

Please find the fix available here: https://github.com/SaveTheChildrenUK/CostOfTheDiet/releases/tag/v2.3.2

Apologies for making it a new version, you'll need to download and install.

Thanks,
Jason

**Comment by jlhems** [comment]
No problem, thanks Jason. Will this be the case each time there's a fix? It overwrites any new assessments I add. Fine right now because I'd hardly entered any data but once I've started to add more it will be very time-consuming to re-do. 

Thanks,
Jacky

**Comment by Zerodriven** [comment]
Heya,

I can tell you how to take a copy of your database in the future and make it work between versions - auto-updating is on our list of things to actually sort out to stop this problem. We really don't want people having to start data entry every time!

Cheers,
Jason.

**Comment by jlhems** [comment]
Sounds good! What's the best way to work between versions for now? If it's easier to have a quick call I'm around until 3.30 today.

**Comment by jlhems** [comment]
Hi Jason, I've downloaded v2.3.2 but still can't add Markets and getting the same page in above screen shot when I hit the back button, not going back to the main assessments page.
